site_name: Web Labs Documentation
nav:
  - Home: index.md
  - Lab 1:
      - "Task 1": lab-1/task1.md
      - "Task 2": lab-1/task2.md
      - "Task 3": lab-1/task3.md
      - "Task 4": lab-1/task4.md
      - "Task 5": lab-1/task5.md
  - Lab 2:
      - "Hotels": lab-2/hotels.md
  - Lab 3:
      - "School system": lab-3/school_system_api.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
